# Generated by Django 5.2.7 on 2025-11-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
