# Generated by Django 4.2.14 on 2025-12-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0009_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="placement_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Privacy-safe location details for vehicle placement",
                null=True,
            ),
        ),
    ]
