# Generated by Django 5.2.10 on 2026-01-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0010_servicerequest_placement_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("FREE", "Free Access"),
                    ("BASIC", "Basic Plan"),
                    ("PREMIUM", "Premium Plan"),
                    ("ELITE", "Elite Plan"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
