# Generated by Django 5.2.10 on 2026-01-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TWO_WHEELER', 'Two Wheeler'), ('FOUR_WHEELER', 'Four Wheeler')], default='FOUR_WHEELER', max_length=20),
        ),
    ]
