# Generated by Django 4.2.14 on 2026-01-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0014_add_all_vehicle_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="chat_attachments/"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
