# Generated by Django 4.2.14 on 2026-01-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0015_chatmessage_image_alter_chatmessage_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location_name", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=10)),
                (
                    "inventory",
                    models.JSONField(
                        default=dict,
                        help_text="Available parts and prices: {'accelerator_wire': 349}",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="servicequote",
            name="expenses_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="servicequote",
            name="is_final",
            field=models.BooleanField(
                default=False, help_text="True if this is the final fare after service"
            ),
        ),
        migrations.AddField(
            model_name="servicequote",
            name="platform_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="servicequote",
            name="platform_profit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="servicequote",
            name="provider_payout",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="servicequote",
            name="spare_parts_details",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of spare parts used: [{'name': '...', 'price': 100}]",
            ),
        ),
        migrations.AddField(
            model_name="servicequote",
            name="spare_parts_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="servicequote",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_DISPATCH", "Pending Dispatch"),
                    ("DISPATCHED", "Provider En Route"),
                    ("ARRIVED", "Provider Arrived"),
                    ("SERVICE_IN_PROGRESS", "Service in Progress"),
                    ("AWAITING_FINAL_FARE", "Provider Finalizing Fare"),
                    ("FINAL_FARE_PENDING", "Waiting for User Approval of Final Fare"),
                    ("COMPLETED", "Completed & Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING_DISPATCH",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="duration_days",
            field=models.IntegerField(default=45),
        ),
    ]
