# Generated by Django 4.2.14 on 2026-01-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0017_alter_vehicle_vehicle_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="location_name",
            field=models.CharField(
                blank=True,
                help_text="Readable address for the incident location",
                max_length=255,
                null=True,
            ),
        ),
    ]
