# Generated by Django 4.2.14 on 2026-01-22 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0018_servicerequest_location_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleexchange",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Replacement Vehicle Request",
                "verbose_name_plural": "Replacement Vehicle Requests",
            },
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("TOWING", "Towing Service"),
                    ("FLAT_TIRE", "Flat Tire Assistance"),
                    ("BATTERY_JUMP", "Battery Jumpstart"),
                    ("FUEL_DELIVERY", "Fuel Delivery"),
                    ("MECHANIC", "Mechanical Issue"),
                    ("LOCKOUT", "Lockout Service"),
                    ("OTHER", "Other Inquiry"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleexchange",
            name="original_vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="User's original vehicle - assigned by support when processing request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchanges_as_original",
                to="services.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="vehicleexchange",
            name="rental_vehicle",
            field=models.ForeignKey(
                blank=True,
                help_text="Temporary rental vehicle provided - assigned by support",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exchanges_as_rental",
                to="services.vehicle",
            ),
        ),
    ]
