# Generated by Django 5.2.9 on 2026-01-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_device_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging Token for Push Notifications', null=True),
        ),
    ]
