# Generated by Django 4.2.14 on 2026-02-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("booker", "Booker"),
                    ("provider", "Provider"),
                ],
                default="booker",
                max_length=20,
            ),
        ),
    ]
