# Generated by Django 5.2.7 on 2025-10-13 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IoTDevice",
            fields=[
                (
                    "device_id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "last_known_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "last_known_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                ("last_battery_level", models.IntegerField(blank=True, null=True)),
                (
                    "last_signal_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "IoT Device",
                "verbose_name_plural": "IoT Devices",
            },
        ),
    ]
