# Generated by Django 5.2.7 on 2025-10-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("iot_devices", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iotdevice",
            name="paired_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="iot_device",
                to="users.servicebooker",
            ),
        ),
    ]
