# Generated by Django 5.2.7 on 2025-10-13 05:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_DISPATCH", "Pending Dispatch"),
                            ("DISPATCHED", "Provider En Route"),
                            ("ARRIVED", "Provider Arrived"),
                            ("SERVICE_IN_PROGRESS", "Service in Progress"),
                            ("QUOTE_PENDING", "Quote Pending User Approval"),
                            ("COMPLETED", "Completed & Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING_DISPATCH",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent (IoT)"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("customer_notes", models.TextField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        default="APP",
                        help_text="Source: APP, IoT Device, or HELPLINE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FREE", "Free Plan (On-Demand Only)"),
                            ("STANDARD", "Standard Subscription"),
                            (
                                "PREMIUM",
                                "Premium Subscription (24/7 Helpline, Exchange Add-on)",
                            ),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("duration_days", models.IntegerField(default=30)),
                ("is_exchange_eligible", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("PETROL", "Petrol"),
                            ("DIESEL", "Diesel"),
                            ("EV", "Electric Vehicle"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
