# Generated by Django 5.2.7 on 2025-11-24 03:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('services', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Subscription Plan', 'verbose_name_plural': 'Subscription Plans'},
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list, help_text='List of features included in this plan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_requests_per_month',
            field=models.IntegerField(default=0, help_text='0 means unlimited'),
        ),
        migrations.CreateModel(
            name='HelplineCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_start', models.DateTimeField()),
                ('call_end', models.DateTimeField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpline_calls', to='users.servicebooker')),
                ('linked_service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpline_calls', to='services.servicerequest')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_calls', to='users.serviceprovider')),
            ],
            options={
                'verbose_name': 'Helpline Call',
                'verbose_name_plural': 'Helpline Calls',
                'ordering': ['-call_start'],
            },
        ),
        migrations.CreateModel(
            name='ServiceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for the service type', max_digits=8)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance from provider to location', max_digits=6)),
                ('time_estimate_minutes', models.IntegerField(help_text='Estimated time in minutes')),
                ('dynamic_total', models.DecimalField(decimal_places=2, help_text='Total after applying plan rates and distance', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending user approval'), ('ACCEPTED', 'User accepted the quote'), ('REJECTED', 'User rejected the quote')], default='PENDING', max_length=10)),
                ('valid_until', models.DateTimeField(help_text='Quote expiration time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'Service Quote',
                'verbose_name_plural': 'Service Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(help_text='Sent, Failed, etc.', max_length=20)),
                ('gateway_response', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SMS Message Log',
                'verbose_name_plural': 'SMS Message Logs',
                'indexes': [models.Index(fields=['to_number', 'sent_at'], name='services_sm_to_numb_41258b_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('return_location', models.CharField(max_length=255)),
                ('rental_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('REQUESTED', 'User requested exchange'), ('PROVIDED', 'Rental vehicle provided'), ('COMPLETED', 'Exchange completed'), ('CANCELLED', 'Exchange cancelled')], default='REQUESTED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_original', to='services.vehicle')),
                ('rental_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_rental', to='services.vehicle')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'Vehicle Exchange',
                'verbose_name_plural': 'Vehicle Exchanges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('REQUESTED', 'Placement requested'), ('IN_PROGRESS', 'Vehicle being moved'), ('COMPLETED', 'Placement done'), ('CANCELLED', 'Placement cancelled')], default='REQUESTED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'Vehicle Placement',
                'verbose_name_plural': 'Vehicle Placements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating 1-5')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicebooker')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceprovider')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='services.servicerequest')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'indexes': [models.Index(fields=['rating'], name='services_re_rating_782255_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending Payment')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='payments.transaction')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='services.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.servicebooker')),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='services_us_user_id_363b6e_idx'), models.Index(fields=['status'], name='services_us_status_1aa630_idx'), models.Index(fields=['end_date'], name='services_us_end_dat_29fe6a_idx')],
            },
        ),
    ]
