# Generated by Django 5.2.7 on 2025-11-24 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_usersubscription_end_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardsProgram',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rewards', serialize=False, to='users.servicebooker')),
                ('points', models.IntegerField(default=0, help_text='Loyalty points earned')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze - 0-499 points'), ('SILVER', 'Silver - 500-1499 points'), ('GOLD', 'Gold - 1500+ points')], default='BRONZE', max_length=20)),
                ('total_services_used', models.IntegerField(default=0)),
                ('referral_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('referrals_made', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rewards Program',
                'verbose_name_plural': 'Rewards Programs',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to='users.servicebooker')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current wallet balance in INR', max_digits=10)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total rewards earned', max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent from wallet', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Points Earned'), ('REDEEMED', 'Points Redeemed'), ('EXPIRED', 'Points Expired'), ('BONUS', 'Bonus Points')], max_length=10)),
                ('description', models.TextField()),
                ('points_balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rewards_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.rewardsprogram')),
            ],
            options={
                'verbose_name': 'Reward Transaction',
                'verbose_name_plural': 'Reward Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Money Added'), ('DEBIT', 'Money Spent'), ('REWARD', 'Reward Earned'), ('REFUND', 'Refund Received')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='services.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
