# Generated by Django 4.2.14 on 2025-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_rewardsprogram_wallet_rewardtransaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_requests_per_month",
            field=models.IntegerField(
                db_column="max_requests_per_month",
                default=0,
                help_text="0 means unlimited",
            ),
        ),
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="max_requests_per_month",
            new_name="max_requests",
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("PENDING", "Pending Payment"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
