# Generated by Django 4.2.14 on 2025-12-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0006_alter_subscriptionplan_max_requests_per_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_requests",
                to="services.vehicle",
            ),
        ),
    ]
