# Generated by Django 4.2.14 on 2025-12-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0007_servicerequest_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="insurance_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="puc_expiry",
            field=models.DateField(blank=True, null=True),
        ),
    ]
