# Generated by Django 5.2.7 on 2025-10-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("settlement_date", models.DateField(unique=True)),
                (
                    "total_platform_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_provider_payout_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("transaction_count", models.IntegerField(default=0)),
                ("status", models.CharField(default="PROCESSED", max_length=20)),
                ("processed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total amount paid by the customer.",
                        max_digits=10,
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "provider_payout",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Payment"),
                            ("SUCCESS", "Payment Successful"),
                            ("FAILED", "Payment Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UPI", "UPI"),
                            ("CARD", "Card"),
                            ("WALLET", "Wallet"),
                            ("CASH", "Cash"),
                        ],
                        default="UPI",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "settled",
                    models.BooleanField(
                        default=False,
                        help_text="True if included in a daily settlement.",
                    ),
                ),
            ],
        ),
    ]
