# Generated by Django 4.2.14 on 2025-11-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="platform_fee",
            new_name="platform_commission",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="provider_payout",
            new_name="provider_payout_amount",
        ),
        migrations.AddField(
            model_name="transaction",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
