# Generated by Django 4.2.14 on 2026-01-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_notification"),
        (
            "payments",
            "0003_rename_platform_fee_transaction_platform_commission_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="booker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_made",
                to="users.servicebooker",
            ),
        ),
    ]
