# Generated by Django 5.2.7 on 2025-10-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("services", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="booker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_made",
                to="users.servicebooker",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments_received",
                to="users.serviceprovider",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="service_request",
            field=models.OneToOneField(
                help_text="The request this payment fulfills.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction",
                to="services.servicerequest",
            ),
        ),
    ]
